spring.application.name=accountmanager

# database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/accountmanagerdb
spring.datasource.username=amuser
spring.datasource.password=ampassword
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=never

logging.level.liquibase=DEBUG

